[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.38", default-features = false }
quote = "1.0.18"
sea-orm = { version = "0.8.0", features = ["sqlx-mysql", "runtime-tokio-rustls"] }
serde = { version = "1.0.137", features = ["derive"] }
syn = { version = "1.0.93", features = ["full"] }
symbols = "0.1.8"
tokio = "1.18.2"
