[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
chrono = "0.4.19"
proc-macro2 = { version = "1.0.37", default-features = false }
quote = "1.0.17"
sea-orm = { version = "0.7.1", features = ["sqlx-mysql", "runtime-tokio-rustls"] }
serde = { version = "1.0.137", features = ["derive"] }
syn = { version = "1.0.91", features = ["full"] }
symbols = { path = "../symbols" }
symbols-models = { path = "../symbols-models" }
tokio = "1.17.0"
