[package]
name = "symbols"
version = "0.1.2"
edition = "2021"
authors = ["Marco Napetti"]
repository = "https://github.com/nappa85/symbols"
readme = "../README.md"
license = "WTFPL"
description = "Proc-macro utility to populate enums from database data"
categories = ["data-structures", "development-tools::procedural-macro-helpers", "database"]
keywords = ["proc-macro", "enum", "database"]

[dependencies]
bincode = "1.3.3"
heck = "0.4.0"
itertools = "0.10.3"
proc-macro2 = { version = "1.0.38", default-features = false }
quote = "1.0.18"
sea-orm = "0.8.0"
serde = "1.0.137"
syn = { version = "1.0.93", features = ["full"] }
symbols-models = "0.1.2"
