[package]
name = "symbols"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
heck = "0.4.0"
itertools = "0.10.3"
proc-macro2 = { version = "1.0.37", default-features = false }
quote = "1.0.17"
sea-orm = "0.7.1"
serde = "1.0.136"
syn = { version = "1.0.91", features = ["full"] }
symbols-models = { path = "../symbols-models" }
